# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI with Ant

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Ant
      run: ant build

    - name: Create JAR file
      run: jar cvf DashOfDimensions.jar -C build/classes .

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: DashOfDimensions
        path: DashOfDimensions.jar

